package com.pojo;

import java.util.Date;

/**
 *  generated by Sanjay
 */
public class ReportPojo{

	private String id;
	private String latitude;
	private String longitude;
	private String name;
	private String unit;
	private String comment;
	private String year;
	private Date date;
	private String url;
	private String param1;
	private String param2;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getLatitude() {
		return latitude;
	}
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}
	public String getLongitude() {
		return longitude;
	}
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public String getYear() {
		return year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getParam1() {
		return param1;
	}
	public void setParam1(String param1) {
		this.param1 = param1;
	}
	public String getParam2() {
		return param2;
	}
	public void setParam2(String param2) {
		this.param2 = param2;
	}
	@Override
	public String toString() {
		return "ReportPojo [" + (id != null ? "id=" + id + ", " : "")
				+ (latitude != null ? "latitude=" + latitude + ", " : "")
				+ (longitude != null ? "longitude=" + longitude + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (unit != null ? "unit=" + unit + ", " : "")
				+ (comment != null ? "comment=" + comment + ", " : "")
				+ (year != null ? "year=" + year + ", " : "")
				+ (date != null ? "date=" + date + ", " : "")
				+ (url != null ? "url=" + url + ", " : "")
				+ (param1 != null ? "param1=" + param1 + ", " : "")
				+ (param2 != null ? "param2=" + param2 : "") + "]";
	}
	
	

}
